### ISSUE TITLE
Impossible d'installer le connecteur

### ISSUE THREAD

**Issue by jmleroux** [hicham-sabihi/aliznet_wcs_connector#4]
Bonjour @hicham-sabihi ,

Comme ce repo n'est que temporaire, je switche en français. Ce sera plus simple pour nos premiers échanges.

J'ai essayer d'installer le connecteur avec une PIM Community Standard, mais il ne fonctionne pas.

J'ai cette erreur : 
```
ClassNotFoundException in CsvWriter.php line 18:
Attempted to load class "CsvWriter" from namespace "Aliznet\WCSBundle\Writer\File".
Did you forget a "use" statement for another namespace?
```
Il y a un problème de nommage de la classe `ProductCsvWriter` qui est dans un fichier `CsvWriter.php`. Ce nommage ne fonctionnera pas avec un autoloader PSR-4 (ni même PSR-0).

**Comment by aliznet-labs** [comment]
Bonjour @jmleroux ,

On vient de mettre à jour notre code (\src), bien sure on corrigeant CsvWriter.php.
On a pas encore corriger composer.json c'est en cours.
Je vous laisse jeter un coup d’œil, j’attendrais vous retours.

Merci,

**Comment by jmleroux** [comment]
Bonjour @hicham-sabihi ,

Nous avançons, mais cette fois j'ai une autre erreur : 

Cela provient de cette classe qui est inconnue : https://github.com/hicham-sabihi/aliznet_wcs_connector/blob/master/src/Aliznet/WCSBundle/Resources/config/readers.yml#L6

Cela arrive souvent quand on réorganise ses namespaces, et c'est le genre d'erreur qui serait très rapidement détectée par des tests unitaires avec PHPSpec ;)

**Comment by jmleroux** [comment]
J'ai eu une erreur d'accès à la base de données car je n'avais pas mis à jour mon schéma.
Mais je ne peux pas le faire via doctrine : 
```
[Doctrine\DBAL\DBALException]                                                                                                                                  
  An exception occurred while executing 'ALTER TABLE oro_user ADD CONSTRAINT FK_F82840BCD654B1EE FOREIGN KEY (defaultTree_id) REFERENCES Category (id)':         
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`pim_sandbox_pcstd`.`#sql-48d_50`, CO  
  NSTRAINT `FK_F82840BCD654B1EE` FOREIGN KEY (`defaultTree_id`) REFERENCES `Category` (`id`)) 
```
Comment avez-vous prévu de mettre à jour le schema de la BDD ?

**Comment by mejdoubimeriem** [comment]
Bonjour @jmleroux ,

On n'a pas encore prévu la mise à jour de la BD,pour le moment tu peux importer les données des deux tables pim_catalog_category et pim_catalog_category_translation vers les deux nouvelle tables : Category et Category_Translation.

Merci d'avance
Mejdoubi Meriem

**Comment by jmleroux** [comment]
Bonjour @mejdoubimeriem ,

Tu veux dire que je dois copier les tables pim_ vers ldeux nouvelles avec les noms que tu m'as donné ?

**Comment by jmleroux** [comment]
ok, je n'avsi pas vu que les tables étaient déjà créées.
Je dois donc effectivement importer les données des deux autres tables.

**Comment by jmleroux** [comment]
Bonjour,

Je n'arrive toujours pas à utiliser l'extension car il manque une colonne `foreign_key`dans la table des Category_Translation.
A terme, vous devrez utiliser les tables existantes du PIM : pim_catalog_category et pim_catalog_category_extension. Pourquoi ne pas d'ores et déjà les utiliser ?

Par ailleurs, je vois que vous modifier la structure du bundle dans le bon sens, félicitations :+1:

**Comment by hicham-sabihi** [comment]
Bonjour @jmleroux 

Merci pour tes retours.
En fait on avait suivi le tutoriel mis pas Akeneo sur le CookBook [http://docs.akeneo.com/1.5/cookbook/category/add-properties-to-category.html] pour ajouter des nouveaux champs sur l'interface Catégorie.
Pour le foreing_key est ce que t'a pu récupérer le override dans le fichier de config.yml :
voir [https://github.com/hicham-sabihi/aliznet_wcs_connector#update-your-configyml]

**Comment by jmleroux** [comment]
C'est OK pour l'override et la structure de table.
Par contre, je ne trouve pas ce fichier de migration : `WCSBundle/Resources/sql/mapping_migration.schema.sql`

**Comment by hicham-sabihi** [comment]
Bonjour @jmleroux 

Je viens de mettre à jour notre git avec le script de migration et les fichiers d'imports.
