### ISSUE TITLE
Questions fonctionnelles

### ISSUE THREAD

**Issue by jmleroux** [hicham-sabihi/aliznet_wcs_connector#5]
Bonjour à tous,

J'ai installé le connector en copiant mes tables de catégories et ça tourne.
L'organisation du bundle et les docs commencent à avoir une forme bien sympa. :+1: 

J'ai deux questions sur l'écran des catégories : 
![screenshot from 2016-04-04 10 04 43](https://cloud.githubusercontent.com/assets/1516770/14241853/407ac1b2-fa4e-11e5-9a9e-66433f107663.png)

La section `name` est-elle nécessaire ? Il me semble que cela fait double emploi avec la section 'node value' (même si cette dernière pourrait être renommée) ?

Le switch `display` est spécifique à Websphère et ne devrait pas être géré au niveau du PIM car il ne s'agit pas d'une donnée multicanal.

**Comment by hicham-sabihi** [comment]
Bonjour @jmleroux 

Oui je suis tout a fait d'accord par l'inutilité de champs Name, on va essayer de renommer node values par name values.

Pour Display c'est un champ de Websphere commerce qui sert à afficher la catégorie en question ou la cacher sur le Front. Cette fonctionnalité doit être présente sur le fichier d'export comme sur les autres champs.

**Comment by jmleroux** [comment]
> Pour Display c'est un champ de Websphere commerce qui sert à afficher la catégorie en question ou la cacher sur le Front. Cette fonctionnalité doit être présente sur le fichier d'export comme pour les autres champs.

Ne pourrait-il pas être géré de la même façon que les `facettable` et autre switch du même style ?

**Comment by jmleroux** [comment]
> Oui je suis tout a fait d'accord par l'inutilité de champs Name, on va essayer de renommer node values par name values.

Je ne pense pas qu'il soit nécessaire de le renommer au sein du PIM. Le transformer lors de l'export serait suffisant.

**Comment by jmleroux** [comment]
> Oui on pourra envisager de la mettre figer dans l'export, mais j'ai une petite question sur les switch, pourquoi n'a t'il pas possible de les utiliser sur le PIM ?

Ce n'est pas une impossibilité technique, mais plutôt fonctionnelle. Le PIM gère les informations qui sont communes à tous les canaux, c'est à dire qu'elles sont potentiellement utilses à plusieurs canaux.
Si une information est vraiement spécifique à un canal, elle n'a pas vocation à être gérée au sein du PIM.

_PS : merci de me répondre dans un commentaire séparé. La discussion va être difficile à suivre si vous repondez en éditant mes questions ;)_

**Comment by hicham-sabihi** [comment]
OK c'est clair.
Merci pour l'information.
