### ISSUE TITLE
Fichiers inutiles

### ISSUE THREAD

**Issue by jmleroux** [hicham-sabihi/aliznet_wcs_connector#6]
Maintenant que la documentation est bien avancée, je pense que certains fichiers inutiles peuvent être supprimés : 

- [aliznet-wcs-connector-structure.txt](https://github.com/hicham-sabihi/aliznet_wcs_connector/blob/master/aliznet-wcs-connector-structure.txt)
- [dossier `app/config`](https://github.com/hicham-sabihi/aliznet_wcs_connector/tree/master/app/config)

**Comment by hicham-sabihi** [comment]
C'est fait, Merci :+1:
